---
- name: include platform vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
  tags: ['timezone']

- name: Install tzdata
  package:
    name: "{{ timezone_package }}"
    state: present
  tags: ['timezone']
  become: true

- name: Set timezone config
  template:
    src: "timezone-{{ ansible_os_family }}.j2"
    dest: "{{ timezone_file }}"
    mode: 0644
    owner: root
    group: root
  tags: ['timezone']
  become: true

- name: Set link to localtime
  file:
    state: link
    src: "{{ zoneinfo_dir }}{{ timezone }}"
    dest: "{{ localtime_file }}"
    force: true
    mode: 0777
    owner: root
    group: root
  tags: ['timezone']
  become: true
