---
- name: include platform vars
  include_vars: "{{ item }}"
  with_first_found:
    - "../vars/{{ ansible_distribution }}.yml"
    - "../vars/{{ ansible_os_family }}.yml"
  tags: ['timezone']

- name: Install tzdata
  package:
    name: "{{ timezone_package }}"
    state: present
  tags: ['timezone']
  become: true

- name: Get properties of "{{ timezone_file }}"
  stat:
    path: "{{ timezone_file }}"
  register: timezone_file_info

# on reconfiguration, /var/lib/dpkg/info/tzdata.config will convert
# the timezone. Eg US/Central to America/Chicago, so try to handle that
# As a side effect, this will also avoid going back to UTC TZ on package
# reconfiguration. See also Debian bugs mentionned later
- name: override timezone configuration
  block:
    - name: Get tz name as converted by tzdata postinst script
      script: ./file/convert_tz.sh "{{ timezone }}"
      args:
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: timezone_conv_tz
    - name: Set new tz
      set_fact:
        timezone: "{{ timezone_conv_tz.stdout | default(timezone) | trim }}"
  when:
    - ansible_os_family == "Debian"

- name: Set timezone config
  template:
    src: "timezone-{{ ansible_os_family }}.j2"
    dest: "{{ timezone_file }}"
    mode: 0644
    owner: root
    group: root
  tags: ['timezone']
  become: true
  register: timezone_tzconfig
  when:
    - timezone_file_info.stat.exists

- name: Set link to localtime
  file:
    state: link
    src: "{{ zoneinfo_dir }}{{ timezone }}"
    dest: "{{ localtime_file }}"
    force: true
    mode: 0644
    owner: root
    group: root
  tags: ['timezone']
  become: true

# Correct way to configure TZ through tzdata package on Debian:
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813226#10
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=848143#10
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=603809
- name: reconfigure tzdata to ensure right configuration.
  command: dpkg-reconfigure -f noninteractive tzdata
  become: true
  when:
    - ansible_os_family == "Debian"
    - timezone_tzconfig is changed
