---
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
dependency:
  name: galaxy
  requirements_file: requirements.yml
driver:
  name: docker
verifier:
  name: ansible
platforms:
  - name: timezone-centos7
    image: centos:7
    privileged: true
  - name: timezone-debian
    image: debian
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
