---
- hosts: all
  tasks:
  - name: Get infos about /etc/localtime
    stat:
      path: /etc/localtime
    register: s_localtime
  - name: Check /etc/localtime
    assert:
      that:
        - s_localtime.stat.exists
        - s_localtime.stat.islnk
        - s_localtime.stat.pw_name == 'root'
        - s_localtime.stat.gr_name == 'root'
        - s_localtime.stat.mode == '0777'
  - name: Get infos about /usr/share/zoneinfo
    stat:
      path: /usr/share/zoneinfo
    register: s_zoneinfo
  - name: Check /usr/share/zoneinfo
    assert:
      that:
        - s_zoneinfo.stat.exists
        - s_zoneinfo.stat.isdir
        - s_zoneinfo.stat.pw_name == 'root'
        - s_zoneinfo.stat.gr_name == 'root'
        - s_zoneinfo.stat.mode == '0755'
  - name: Get timezone
    command: date +'%Z'
    changed_when: false
    register: cur_date
  - name: Validate timezone
    assert:
      that:
        - cur_date.stdout == "-03"
  - name: Validate debian configuration
    block:
      - name: get debconf
        command: debconf-show tzdata
        register: debconf
      - name: Check debconf output content
        assert:
          that:
            - '"tzdata/Zones/America: Argentina/Catamarca" in debconf.stdout'
            - '"tzdata/Areas: America" in debconf.stdout'
    when:
      - ansible_os_family == "Debian"
